import type { Config } from "tailwindcss";

/**
 * All color/typography values reference CSS variables defined in
 * styles/tokens.css — the single place brand values live (SPEC §4).
 */
const config: Config = {
  content: [
    "./app/**/*.{ts,tsx,mdx}",
    "./components/**/*.{ts,tsx}",
    "./content/**/*.mdx",
  ],
  theme: {
    extend: {
      colors: {
        bg: "rgb(var(--color-bg-rgb) / <alpha-value>)",
        surface: "rgb(var(--color-surface-rgb) / <alpha-value>)",
        ink: "var(--color-ink)",
        "ink-mid": "var(--color-ink-mid)",
        "ink-soft": "var(--color-ink-soft)",
        line: "var(--color-line)",
        accent: "var(--color-accent)",
        "accent-ink": "var(--color-accent-ink)",
        "tag-podcast": "var(--tag-podcast)",
        "tag-article": "var(--tag-article)",
        "tag-data": "var(--tag-data)",
        "tag-chart": "var(--tag-chart)",
        "tag-video": "var(--tag-video)",
        "tag-social": "var(--tag-social)",
        "tag-quote": "var(--tag-quote)",
        "tag-mvp": "var(--tag-mvp)",
        success: "var(--color-success)",
        warning: "var(--color-warning)",
        error: "var(--color-error)",
        info: "var(--color-info)",
        fdr: {
          1: "var(--fdr-1)",
          2: "var(--fdr-2)",
          3: "var(--fdr-3)",
          4: "var(--fdr-4)",
          5: "var(--fdr-5)",
          unknown: "var(--fdr-unknown)",
        },
        "surface-card": "var(--surface-card)",
        "surface-deep": "var(--surface-deep)",
        "surface-card-ink": "var(--surface-card-ink)",
        "surface-card-ink-mid": "var(--surface-card-ink-mid)",
        "surface-card-border": "var(--surface-card-border)",
        "brand-navy-deep": "var(--bf-navy-deep)",
        "brand-navy": "var(--bf-navy)",
        "brand-teal": "var(--bf-teal)",
        "brand-cyan": "var(--bf-cyan)",
        "brand-turquoise": "var(--bf-turquoise)",
        "brand-salmon": "var(--bf-salmon)",
        "brand-coral": "var(--bf-coral)",
        "brand-crimson": "var(--bf-crimson)",
        "brand-gold": "var(--bf-gold)",
        "brand-mustard": "var(--bf-mustard)",
        "brand-brown": "var(--bf-brown)",
        "brand-gray": "var(--bf-gray)",
        "theme-lightest-1-bg": "var(--theme-lightest-1-bg)",
        "theme-lightest-1-ink": "var(--theme-lightest-1-ink)",
        "theme-lightest-2-bg": "var(--theme-lightest-2-bg)",
        "theme-lightest-2-ink": "var(--theme-lightest-2-ink)",
        "theme-light-1-bg": "var(--theme-light-1-bg)",
        "theme-light-1-ink": "var(--theme-light-1-ink)",
        "theme-light-2-bg": "var(--theme-light-2-bg)",
        "theme-light-2-ink": "var(--theme-light-2-ink)",
        "theme-bright-1-bg": "var(--theme-bright-1-bg)",
        "theme-bright-1-ink": "var(--theme-bright-1-ink)",
        "theme-bright-2-bg": "var(--theme-bright-2-bg)",
        "theme-bright-2-ink": "var(--theme-bright-2-ink)",
        "theme-dark-1-bg": "var(--theme-dark-1-bg)",
        "theme-dark-1-ink": "var(--theme-dark-1-ink)",
        "theme-dark-2-bg": "var(--theme-dark-2-bg)",
        "theme-dark-2-ink": "var(--theme-dark-2-ink)",
        "theme-darkest-1-bg": "var(--theme-darkest-1-bg)",
        "theme-darkest-1-ink": "var(--theme-darkest-1-ink)",
        "theme-darkest-2-bg": "var(--theme-darkest-2-bg)",
        "theme-darkest-2-ink": "var(--theme-darkest-2-ink)",
      },
      fontFamily: {
        display: "var(--font-display)",
        sans: "var(--font-sans)",
        badge: "var(--font-montserrat)",
        buttons: "var(--font-buttons)",
        misc: "var(--font-misc)",
      },
      fontSize: {
        base: "var(--font-size-base)",
      },
      letterSpacing: {
        kicker: "var(--tracking-kicker)",
        display: "var(--tracking-display)",
      },
      borderRadius: {
        tile: "var(--radius-tile)",
        pill: "var(--radius-pill)",
      },
      boxShadow: {
        tile: "var(--shadow-tile)",
        lifted: "var(--shadow-lifted)",
      },
      transitionTimingFunction: {
        brand: "var(--motion-ease)",
      },
      transitionDuration: {
        fast: "var(--motion-fast)",
        base: "var(--motion-base)",
        slow: "var(--motion-slow)",
      },
    },
  },
  plugins: [],
};

export default config;
